version: '3.3'

networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

services:
  wai-vis-dd:
    image: tethysts/tethys-wai-vis-dd:1.5
    environment:
      - VARIABLE_NAME=server
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # depends_on:
    #   - "web-service"
    # ports:
    #   - "8081:80"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.function == web_server
          # - node.hostname == esnode2.nzrivers.xyz
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.tethys-wai-dd-http.rule=Host(`dd.tethys-ts.xyz`)
        - traefik.http.routers.tethys-wai-dd-http.entrypoints=http
        - traefik.http.routers.tethys-wai-dd-https.rule=Host(`dd.tethys-ts.xyz`)
        - traefik.http.routers.tethys-wai-dd-http.middlewares=https-redirect
        - traefik.http.routers.tethys-wai-dd-https.entrypoints=https
        - traefik.http.routers.tethys-wai-dd-https.tls=true
        # - traefik.http.routers.tethys-wai-https.tls.certresolver=le
        - traefik.http.services.tethys-wai-dd.loadbalancer.server.port=80
