version: '3.3'

# networks:
#   net:
#     driver: overlay
#     attachable: true
#   traefik-public:
#     external: true

services:
  wai-vis:
    image: tethysts/tethys-wai-vis-dd:1.5
    # environment:
    #   - VARIABLE_NAME=server
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # depends_on:
    #   - "web-service"
    ports:
      - "8000:80"
    # # volumes:
    # #   - /var/run/docker.sock:/var/run/docker.sock:ro
    # networks:
    #   # - net
    #   - traefik-public
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role == manager
    #   labels:
    #     - traefik.enable=true
    #     - traefik.docker.network=traefik-public
    #     - traefik.constraint-label=traefik-public
    #     - traefik.http.routers.tethys-wai-http.rule=Host(`${DOMAIN2?Variable not set}`)
    #     - traefik.http.routers.tethys-wai-http.entrypoints=http
    #     - traefik.http.routers.tethys-wai-http.middlewares=https-redirect
    #     - traefik.http.routers.tethys-wai-https.rule=Host(`${DOMAIN2?Variable not set}`)
    #     - traefik.http.routers.tethys-wai-https.entrypoints=https
    #     - traefik.http.routers.tethys-wai-https.tls=true
    #     - traefik.http.routers.tethys-wai-https.tls.certresolver=le
    #     - traefik.http.services.tethys-wai.loadbalancer.server.port=80
