sudo: required

services:
  - docker

env:
  global:
    CACHE_IMAGE: tethysts/tethys-wai-vis:$TRAVIS_BRANCH

before_script:
  - docker pull $CACHE_IMAGE || true

script:
  - docker build --cache-from $CACHE_IMAGE --tag $CACHE_IMAGE .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $CACHE_IMAGE
